version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_permissions_enabled=false
    volumes:
      - namenode_data:/hadoop/dfs/name
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - HDFS_CONF_dfs_permissions_enabled=false
    volumes:
      - datanode_data:/hadoop/dfs/data
    depends_on:
      - namenode

  flume:
    image: probablyfine/flume:latest
    container_name: flume
    environment:
      - FLUME_AGENT_NAME=agent
    volumes:
      - ./flume/flume.conf:/opt/flume-config/flume.conf
      - ./flume/spooldir:/spooldir
    command: ["flume-ng", "agent", "-n", "agent", "-f", "/opt/flume-config/flume.conf", "-Dflume.root.logger=INFO,console"]
    depends_on:
      - namenode

  log_generator:
    build: ./loggen
    container_name: loggen
    volumes:
      - ./flume/spooldir:/spooldir    # generator writes directly to this folder
      - ./flume/tmp:/tmp              # matches your Python script
    depends_on:
      - flume

volumes:
  namenode_data:
  datanode_data:
