version: '3.8'

services:
 
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hdfs_namenode:/hadoop/dfs/name

  # =======================
  # HDFS DATANODE
  # =======================
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    ports:
      - "50075:50075"
    volumes:
      - hdfs_datanode:/hadoop/dfs/data

  

  
  flume:
    build: ./flume
    container_name: flume
    volumes:
      - ./flume/spooldir:/spooldir
      - ./flume/conf:/opt/flume/conf
    environment:
      JAVA_HOME: /opt/java/openjdk   # ajuste selon ton Dockerfile / JDK
    command: >
      /opt/flume/bin/flume-ng agent
      -n agent
      -f /opt/flume/conf/flume.conf
      --conf /opt/flume/conf
      -Dflume.root.logger=INFO,console




  log_generator:
    build: ./loggen
    container_name: loggen
    volumes:
      - ./flume/spooldir:/spooldir    # generator writes directly to this folder
      - ./flume/tmp:/tmp              # matches your Python script
    depends_on:
      - flume  

volumes:
  hdfs_namenode:
  hdfs_datanode:
