apiVersion: 1
datasources:
  - name: MySQL-Analytics
    type: mysql
    access: proxy
    url: mysql:3306
    database: analytics
    user: user
    secureJsonData:
      password: password
    isDefault: true
