# Nom de l'agent
agent.sources = spool-source
agent.sinks = hdfs-sink
agent.channels = mem-channel

# Configuration de la source
agent.sources.spool-source.type = spooldir
agent.sources.spool-source.spoolDir = /spooldir
agent.sources.spool-source.channels = mem-channel

# Configuration du channel
agent.channels.mem-channel.type = memory
agent.channels.mem-channel.capacity = 10000
agent.channels.mem-channel.transactionCapacity = 1000

# Configuration du sink
agent.sinks.hdfs-sink.type = hdfs
agent.sinks.hdfs-sink.hdfs.path = hdfs://namenode:9000/flume/events
agent.sinks.hdfs-sink.hdfs.fileType = DataStream
agent.sinks.hdfs-sink.channel = mem-channel
